#ifndef DEM_EVENT_LIST
#define DEM_EVENT_LIST

enum 
{
        Dem_Event_ID_PWM_LIGHTCONTROLLER_PWM_WARMWHITE_UPDATE_FAILED,
#define Dem_Event_Threshold_PWM_LIGHTCONTROLLER_PWM_WARMWHITE_UPDATE_FAILED 1u
        Dem_Event_ID_PWM_LIGHTCONTROLLER_PWM_COLDWHITE_UPDATE_FAILED,
#define Dem_Event_Threshold_PWM_LIGHTCONTROLLER_PWM_COLDWHITE_UPDATE_FAILED 1u

};


#endif