name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

      # Builds project specified in pre_run_setup
    - name: Build project
      run:  |
        echo "Entering directory $PROJECT_BUILD"
        cd $PROJECT_BUILD
        cmake ..
        make
        cd -
